import { readFileSync, writeFileSync } from "node:fs";
import { desc, eq, sql } from "drizzle-orm";
import { getDb } from "../lib/db";
import { loadLocalEnv } from "../lib/env";
import { events, leads, outreach } from "../lib/db/schema";

/**
 * Regenerates the Log table in memory/OUTREACH-LOG.md from the database.
 *
 * The file is the human-readable mirror; `outreach` and `events` are the truth.
 * Maintaining it by hand guarantees it drifts, and a log that disagrees with the
 * data is worse than none — the weekly review would be reasoning from it.
 *
 * Only the table between the markers is rewritten, so the rules and the angle
 * list above it survive.
 */
const FILE = "memory/OUTREACH-LOG.md";
const START = "## Log";
const END = "## Angles in use";

function fmt(d: Date | null): string {
  return d ? d.toISOString().slice(0, 10) : "";
}

async function main() {
  loadLocalEnv();
  const db = getDb();

  const rows = await db
    .select({
      company: leads.company,
      title: leads.title,
      angle: outreach.angle,
      proofUsed: outreach.proofUsed,
      createdAt: outreach.createdAt,
      sentAt: outreach.sentAt,
      leadId: sql<string>`${outreach.leadId}`,
      step: outreach.step,
    })
    .from(outreach)
    .innerJoin(leads, eq(leads.id, outreach.leadId))
    .orderBy(desc(outreach.createdAt));

  const outcomes = await db
    .select({ leadId: events.leadId, type: events.type, at: events.createdAt })
    .from(events)
    .orderBy(desc(events.createdAt));

  const latestOutcome = new Map<string, string>();
  for (const e of outcomes) {
    if (!e.leadId) continue;
    if (["reply", "call", "won", "lost", "no_reply"].includes(e.type)) {
      if (!latestOutcome.has(e.leadId)) latestOutcome.set(e.leadId, e.type);
    }
  }

  const header = "| Date | Company | Role | Angle | Proof led with | Outcome | Notes |\n|---|---|---|---|---|---|---|";
  const body = rows.length
    ? rows
        .map((r) => {
          const outcome = latestOutcome.get(r.leadId) ?? (r.sentAt ? "awaiting" : "not sent");
          const proof = (r.proofUsed ?? []).join("; ");
          const note = r.step > 0 ? `follow-up step ${r.step}` : "";
          return `| ${fmt(r.sentAt ?? r.createdAt)} | ${r.company} | ${r.title} | ${r.angle ?? ""} | ${proof} | ${outcome} | ${note} |`;
        })
        .join("\n")
    : "| _(no drafts written yet)_ | | | | | | |";

  const file = readFileSync(FILE, "utf8");
  const start = file.indexOf(START);
  const end = file.indexOf(END);
  if (start === -1 || end === -1) {
    console.error(`could not find the "${START}" / "${END}" markers in ${FILE}`);
    process.exit(1);
  }

  const rebuilt = `${file.slice(0, start)}${START}\n\nGenerated by \`pnpm log:outreach\` — edit the database, not this table.\n\n${header}\n${body}\n\n${file.slice(end)}`;
  writeFileSync(FILE, rebuilt);

  console.log(`log-outreach: wrote ${rows.length} row(s) to ${FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
